[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F401CCUX"
# runner = "elf2uf2-rs -d"

[build]
target = "thumbv7em-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "trace"
